# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\test_area\add_area.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAddArea(HttpRunner):

    config = Config("库区测试流程").verify(False)

    teststeps = [
        Step(
            RunRequest("添加库区")
            .post("http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/area/save")
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json(
                {
                    "areaCode": "A2",
                    "areaName": "A区2",
                    "areaStatus": 1,
                    "zoneId": "41296896278462465",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取库区Id")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/area/listPage"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json(
                {
                    "current": 1,
                    "paramsList": [],
                    "queryCode": "wms_bas_area_list",
                    "size": 50,
                }
            )
            .extract()
            .with_jmespath("body.data.records[1].id", "id")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("更新库区")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/area/update"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json(
                {
                    "areaCode": "A2",
                    "areaName": "A区22",
                    "areaStatus": 1,
                    "id": "$id",
                    "remark": "",
                    "zoneId": "41296896278462465",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("删除库区")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/area/removeByIds"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json({"ids": ["$id"]})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseAddArea().test_start()
