# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\test_area\list_area.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseListArea(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/asura/wms/web/bas/area/listPage")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/area/listPage"
            )
            .with_headers(
                **{
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsInVuYW1lIjoiYWRtaW4iLCJ1c2VyT3BlcmF0aW9uIjoyLCJjbGllbnQiOiJQQyIsImlzQWRtaW4iOjEsImFwcENvZGUiOiJXTVMiLCJleHAiOjE2NTgyOTE1NzQ4MDgsImJpekdyb3VwQ29kZSI6ImFzdXJhLXdtcy1jbHVzdGVyIn0.CnyrBUFunWLGKB6gDaWzf5P6ZtoSDkjirLWCCTsKCsQ"
                }
            )
            .with_json(
                {
                    "current": 1,
                    "paramsList": [],
                    "queryCode": "wms_bas_area_list",
                    "size": 50,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.code", "0000000")
            .assert_equal("body.msg", "操作成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseListArea().test_start()
