# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\test_bin\add_bin.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAddBin(HttpRunner):

    config = Config("库位测试流程").verify(False)

    teststeps = [
        Step(
            RunRequest("新增库位")
            .post("http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/bin/save")
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json(
                {
                    "abcType": 1,
                    "areaId": "40930757996191745",
                    "binCode": "A001",
                    "binStatus": 0,
                    "binType": 1,
                    "isStorageLimit": 0,
                    "lotLimitType": 1,
                    "pickRoute": "ac",
                    "putawayRoute": "as",
                    "storageType": 0,
                    "useType": 1,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取库位id")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/bin/listPage"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json(
                {
                    "current": 1,
                    "paramsList": [],
                    "queryCode": "wms_bas_bin_list",
                    "size": 50,
                }
            )
            .extract()
            .with_jmespath("body.data.records[2].id", "id")
            .validate()
            .assert_equal("body.msg", "操作成功")
        ),
        Step(
            RunRequest("启用库位")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/bin/setEnable"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json({"ids": ["$id"]})
            .validate()
            .assert_equal("body.msg", "操作成功")
        ),
        Step(
            RunRequest("停用库位")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/bin/setDisable"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json({"ids": ["$id"]})
            .validate()
            .assert_equal("body.msg", "操作成功")
        ),
        Step(
            RunRequest("更新库位状态为草稿")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/bin/update"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json(
                {
                    "abcType": 1,
                    "areaId": "40930757996191745",
                    "binCode": "A001",
                    "binStatus": 0,
                    "binType": 1,
                    "columnsNo": "",
                    "height": "0.000000",
                    "id": "$id",
                    "isStorageLimit": 0,
                    "layersNo": "",
                    "length": "0.000000",
                    "lotLimitType": 1,
                    "maxVolume": "0.000000",
                    "maxWeight": "0.000000",
                    "passage": "",
                    "pickRoute": "ac",
                    "putawayRoute": "as",
                    "remark": "",
                    "rowsNo": "",
                    "saleAreaCode": "",
                    "saleAreaLot": "",
                    "storageType": 0,
                    "tradeType": 0,
                    "useType": 1,
                    "width": "0.000000",
                }
            )
            .validate()
            .assert_equal("body.msg", "操作成功")
        ),
        Step(
            RunRequest("删除库位")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/bas/bin/removeByIds"
            )
            .with_headers(**{"token": "${ENV(token)}"})
            .with_json({"ids": ["$id"]})
            .validate()
            .assert_equal("body.msg", "操作成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseAddBin().test_start()
