# NOTE: Generated By HttpRunner v4.1.6
# FROM: har\out_plan\boxCheck_test.json
from httprunner import HttpRunner, Config, Step, RunRequest, RunSqlRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.test_outPlan.cutBox_test_test import   (
    TestCaseCutboxTest as cutBox,
)

class TestCaseBoxcheckTest(HttpRunner):

    config = Config("波次整箱复核")

    teststeps = [
        Step(RunTestCase("波次切箱").call(cutBox).export(*["waveId"])),
        Step(
            RunRequest("")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/out/wave/boxCheck"
            )
            .with_headers(
                **{
                    "Content-Type": "application/json;charset=UTF-8",
                    "bid": "1528936961052135425",
                    "businesscode": "RG20",
                    "businessname": "%E5%8D%8E%E5%8D%97%E6%80%BB%E4%BB%93",
                    "token": "${ENV(token)}",
                    "trace.id": "c80f92fb-0956-c521-a159-2a04989e0773",
                }
            )
            .with_json({"id": "$waveId"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal("body.msg", "操作成功", "assert response body msg")
        ),
        Step(
            RunSqlRequest("查询包裹运单")
            .fetchone("select pack_no from asura_wms_005.out_pack where wave_id = $waveId;")
            .extract()
            .with_jmespath("pack_no", "pack_no")
        ),
    ]


if __name__ == "__main__":
    TestCaseBoxcheckTest().test_start()
