# NOTE: Generated By HttpRunner v4.3.0
# FROM: har\out_plan\confirmById_test.yaml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.test_outPlan.create_wave_test_test import (
    TestCaseCreateWaveTest as creatWaveTest,
)
class TestCaseConfirmbyidTest(HttpRunner):

    config = Config("完成拣货")

    teststeps = [
        Step(RunTestCase("创建波次").call(creatWaveTest).export(*["waveId"])),
        Step(
            RunRequest("")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/out/pick/exe/confirmByWaveId"
            )
            .with_headers(
                **{
                    "Content-Type": "application/json;charset=UTF-8",
                    "bid": "1528936961052135425",
                    "businesscode": "RG20",
                    "businessname": "%E5%8D%8E%E5%8D%97%E6%80%BB%E4%BB%93",
                    "token": "${ENV(token)}",
                    "trace.id": "e2d013c3-5ad0-3826-a227-59719d6fd50d",
                }
            )
            .with_json(
                {
                    "pickUserAccount": "zjx",
                    "pickUserId": "31916896773246978",
                    "pickUserName": "zhengjix",
                    "waveId": "$waveId",
                }
            )
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal("body.msg", "操作成功", "assert response body msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseConfirmbyidTest().test_start()
