# NOTE: Generated By HttpRunner v4.1.6
# FROM: har\out_plan\confirmById_test.json
from httprunner import HttpRunner, Config, Step, RunRequest,RunSqlRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.test_outPlan.create_wave_test_test import (
    TestCaseCreateWaveTest as creatWaveTest,
)



class TestCaseConfirmbyidTest(HttpRunner):

    config = (Config("拣货确认及状态校验")
              .db()
              .user('asura')
              .password("asura")
              .ip("test.mysql8.ruigushop.com")
              .port(3306)
              .database("asura_wms_005"))

    teststeps = [
        Step(RunTestCase("查询波次ID").call(creatWaveTest).export(*["waveId"])),
        Step(
            RunRequest("拣货确认")
            .post(
                "http://test.asura-wms.ruigushop.com/api/asura/wms/web/out/pick/exe/confirmByWaveId"
            )
            .with_headers(
                **{
                    "Content-Type": "application/json;charset=UTF-8","bid": "1528936961052135425",
                    "businesscode": "RG20",
                    "businessname": "%E5%8D%8E%E5%8D%97%E6%80%BB%E4%BB%93",
                    "token": "${ENV(token)}",
                    "trace.id": "7b01ae93-5c82-6c2b-fd51-2e34d2873b36",
                }
            )
            .with_json(
                {
                    "pickUserAccount": "zjx",
                    "pickUserId": "31916896773246978",
                    "pickUserName": "zhengjix",
                    "waveId": "$waveId",
                }
            )
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal("body.msg", "操作成功", "assert response body msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseConfirmbyidTest().test_start()
